(uiop:define-package #:tamei.functions.pure (:use :cl)
  (:export

   ;;
   ;; Arrays
   :make-array
   :vector
   :aref
   :row-major-aref
   :svref
   :array-dimension
   :array-dimensions
   :array-displacement
   :array-rank
   :array-row-major-index
   :array-total-size
   :fill-pointer
   :array-element-type
   :upgraded-array-element-type
   :bit-and
   :bit-andc1
   :bit-andc2
   :bit-eqv
   :bit-ior
   :bit-nand
   :bit-nor
   :bit-not
   :bit-orc1
   :bit-orc2
   :bit-xor
   :sbit
   :adjustable-array-p
   :array-has-fill-pointer-p
   :array-in-bounds-p
   :arrayp
   :bit-vector-p
   :simple-bit-vector-p
   :simple-vector-p
   :vectorp

   ;;
   ;; Conses
   :caaaar
   :caaadr
   :caaar
   :caadar
   :caaddr
   :caadr
   :caar
   :cadaar
   :cadadr
   :cadar
   :caddar
   :cadddr
   :caddr
   :cadr
   :car
   :cdaaar
   :cdaadr
   :cdaar
   :cdadar
   :cdaddr
   :cdadr
   :cdar
   :cddaar
   :cddadr
   :cddadr
   :cddar
   :cdddar
   :cddddr
   :cdddr
   :cddr
   :cdr
   :mapc
   :mapcar
   :nthcdr
   :cons
   :adjoin
   :append
   :get-properties
   :acons
   :assoc
   :assoc-if
   :assoc-if-not
   :copy-alist
   :rassoc
   :rassoc-if
   :rassoc-if-not
   :pairlis
   :sublis
   :first
   :second
   :third
   :fourth
   :fifth
   :sixth
   :seventh
   :eighth
   :ninth
   :tenth
   :copy-list
   :list
   :list*
   :list-length
   :make-list
   :maplist
   :member
   :member-if
   :member-if-not
   :subst
   :subst-if
   :subst-if-not
   :intersection
   :set-difference
   :set-exclusive-or
   :union
   :nth
   :rest
   :last
   :butlast
   :ldiff
   :copy-tree
   :tree-equal
   :atom
   :null
   :endp
   :consp
   :listp
   :tailp
   :subsetp

   ;;
   ;; Data and Control Flow
   :identity
   :complement
   :not
   :eq
   :eql
   :equal
   :equalp
   :apply
   :funcall
   :multiple-value-list
   :values
   :values-list
   :every
   :notany
   :notevery
   :some
   :constantly
   :get-setf-expansion
   :compiled-function-p
   :functionp
   :function-lambda-expression
   :gensym

   ;;
   ;; Hash Tables
   :gethash
   :hash-table-count
   :hash-table-rehash-size
   :hash-table-rehash-threshold
   :hash-table-size
   :hash-table-test
   :make-hash-table
   :sxhash
   :maphash
   :hash-table-p

   ;;
   ;; Numbers
   :>
   :-
   :<=
   :+
   :*
   :<
   :1+
   :/=
   :=
   :>=
   :1-
   :/
   :exp
   :log
   :abs
   :max
   :min
   :boole
   :dpb
   :ldb
   :gcd
   :lcm
   :cis
   :bit
   :ash
   :cos
   :acos
   :acosh
   :cosh
   :sin
   :asin
   :asinh
   :sinh
   :tan
   :atan
   :atanh
   :tanh
   :fceiling
   :ffloor
   :floor
   :fround
   :ftruncate
   :mod
   :rem
   :round
   :truncate
   :decode-float
   :float
   :float-digits
   :float-precision
   :float-radix
   :float-sign
   :integer-decode-float
   :scale-float
   :imagpart
   :realpart
   :upgraded-complex-part-type
   :logand
   :logandc1
   :logandc2
   :logcount
   :logeqv
   :logior
   :lognand
   :lognor
   :lognot
   :logorc1
   :logorc2
   :logtest
   :logxor
   :byte
   :byte-position
   :byte-size
   :expt
   :integer-length
   :isqrt
   :numerator
   :rational
   :rationalize
   :signum
   :sqrt
   :ceiling
   :complex
   :conjugate
   :ldb-test
   :denominator
   :deposit-field
   :mask-field
   :parse-integer
   :phase
   :make-random-state
   :arithmetic-error-operands
   :arithmetic-error-operation
   :random-state-p
   :complexp
   :evenp
   :floatp
   :integerp
   :logbitp
   :minusp
   :numberp
   :oddp
   :plusp
   :rationalp
   :realp
   :zerop

   ;;
   ;; Sequences
   :copy-seq
   :make-sequence
   :subseq
   :concatenate
   :elt
   :map
   :reduce
   :reverse
   :length
   :search
   :mismatch
   :find
   :find-if
   :find-if-not
   :count
   :count-if
   :count-if-not
   :position
   :position-if
   :position-if-not
   :remove
   :remove-duplicates
   :remove-if
   :remove-if-not
   :substitute
   :substitute-if
   :substitute-if-not

   ;;
   ;; Symbols
   :make-symbol
   :copy-symbol
   :symbol-plist
   :symbol-name
   :get
   :getf
   :symbol-package
   :symbolp
   :keywordp

   ;;
   ;; Characters
   :name-char
   :code-char
   :digit-char
   :char-code
   :char-downcase
   :char-equal
   :char-int
   :char-name
   :char-not-equal
   :char-upcase
   :char/=
   :char<
   :char<=
   :char=
   :char>
   :char>=
   :character
   :upper-case-p
   :char-greaterp
   :lower-case-p
   :char-lessp
   :both-case-p
   :char-not-greaterp
   :char-not-lessp
   :characterp
   :alpha-char-p
   :alphanumericp
   :digit-char-p
   :graphic-char-p
   :standard-char-p

   ;;
   ;; Strings
   :schar
   :char
   :make-string
   :string
   :string-capitalize
   :string-downcase
   :string-equal
   :string-left-trim
   :string-not-equal
   :string-right-trim
   :string-trim
   :string-upcase
   :string/=
   :string<
   :string<=
   :string=
   :string>
   :string>=
   :simple-string-p
   :string-greaterp
   :string-lessp
   :string-not-greaterp
   :string-not-lessp
   :stringp

   ;;
   ;; Objects
   :find-class
   :unbound-slot-instance
   :slot-value
   :class-of
   :make-load-form-saving-slots
   :find-method
   :method-qualifiers
   :slot-boundp
   :slot-exists-p

   ;;
   ;; Files
   :file-author
   :file-error-pathname

   ;;
   ;; Packages
   :package-name
   :package-nicknames
   :package-error-package
   :package-shadowing-symbols
   :package-use-list
   :package-used-by-list
   :find-symbol
   :packagep

   ;;
   ;; Environment
   :decode-universal-time
   :encode-universal-time
   :lisp-implementation-version
   :machine-instance
   :machine-type
   :machine-version
   :lisp-implementation-type
   :long-site-name
   :short-site-name
   :software-type
   :software-version

   ;;
   ;; Conditions
   :simple-condition-format-control
   :make-condition
   :restart-name
   :simple-condition-format-arguments
   :cell-error-name
   :invalid-method-error

   ;;
   ;; Streams
   :stream-external-format
   :synonym-stream-symbol
   :broadcast-stream-streams
   :concatenated-stream-streams
   :echo-stream-input-stream
   :echo-stream-output-stream
   :make-broadcast-stream
   :make-concatenated-stream
   :make-echo-stream
   :make-string-input-stream
   :make-string-output-stream
   :make-two-way-stream
   :stream-error-stream
   :two-way-stream-input-stream
   :two-way-stream-output-stream
   :streamp
   :file-string-length

   ;;
   ;; Structures
   :copy-structure

   ;;
   ;; Types and Classes
   :coerce
   :type-of
   :type-error-datum
   :type-error-expected-type
   :subtypep
   :typep

   ;;
   ;; Reader
   :copy-readtable
   :get-dispatch-macro-character
   :get-macro-character
   :readtable-case
   :readtablep

   ;;
   ;; Printer
   :formatter

   ;;
   ;; Filenames
   :merge-pathnames
   :directory-namestring
   :pathname-device
   :pathname-directory
   :pathname-host
   :pathname-match-p
   :pathname-name
   :pathname-type
   :pathname-version
   :pathnamep
   :translate-pathname
   :wild-pathname-p
   :namestring
   :host-namestring
   :file-namestring
   :pathname
   :parse-namestring
   :logical-pathname-translations

   ;;
   ;; Evaluation & Compilation
   :macro-function
   :compiler-macro-function
   :constantp
   :special-operator-p))
