(UNTRACE DECF AND CASE DEFINE-METHOD-COMBINATION DO-EXTERNAL-SYMBOLS
         HANDLER-CASE REMF CALL-METHOD DEFINE-COMPILER-MACRO WITH-OPEN-STREAM
         WITH-COMPILATION-UNIT COND DEFPACKAGE WITH-HASH-TABLE-ITERATOR
         CTYPECASE PPRINT-LOGICAL-BLOCK DEFGENERIC ETYPECASE DEFMACRO POP
         RESTART-CASE DEFCLASS WITH-OUTPUT-TO-STRING ROTATEF WITH-SLOTS
         PPRINT-EXIT-IF-LIST-EXHAUSTED WITH-INPUT-FROM-STRING TYPECASE PSETQ
         PPRINT-POP DECLAIM ASSERT WITH-ACCESSORS HANDLER-BIND DO*
         DEFINE-SETF-EXPANDER WITH-OPEN-FILE WITH-PACKAGE-ITERATOR RESTART-BIND
         DEFUN TRACE PROG1 SETF OR DEFSTRUCT CHECK-TYPE DOLIST STEP UNLESS
         CCASE MULTIPLE-VALUE-SETQ WITH-CONDITION-RESTARTS ECASE SHIFTF LOOP
         FORMATTER TIME LAMBDA DESTRUCTURING-BIND LOOP-FINISH
         MULTIPLE-VALUE-LIST MULTIPLE-VALUE-BIND PRINT-UNREADABLE-OBJECT PROG
         DO-SYMBOLS DO-ALL-SYMBOLS IN-PACKAGE DO PUSHNEW
         WITH-STANDARD-IO-SYNTAX DEFPARAMETER PSETF DOTIMES DEFSETF
         WITH-SIMPLE-RESTART DEFMETHOD NTH-VALUE IGNORE-ERRORS INCF DEFCONSTANT
         WHEN DEFINE-SYMBOL-MACRO PUSH DEFINE-CONDITION PROG* RETURN
         DEFINE-MODIFY-MACRO DEFTYPE DEFVAR PROG2)
