;;;; package containing all the pure forms from common lisp
;;;; functions or macros that do not modify the inputs or perform visible
;;;; flow control, and that only operate on their arguments. e.g. > equal sqrt

(defpackage #:cl-pure
  (:use #:tamei-common)
  (:import-from :cl
                #:*
                #:+
                #:-
                #:/=
                #:1+
                #:1-
                #:<
                #:<=
                #:=
                #:>
                #:>=
                #:abs
                #:acons
                #:acos
                #:acosh
                #:adjoin
                #:adjustable-array-p
                #:allocate-instance
                #:alpha-char-p
                #:alphanumericp
                #:and
                #:append
                #:apply
                #:apropos-list
                #:aref
                #:atanh
                #:atom
                #:bit
                #:caadr
                #:caar
                #:cadaar
                #:cadadr
                #:cadar
                #:caddar
                #:cadddr
                #:caddr
                #:cadr
                #:car
                #:cdaaar
                #:cdaadr
                #:cdaar
                #:cdadar
                #:cdaddr
                #:cdadr
                #:cdar
                #:cddaar
                #:cddadr
                #:cddar
                #:cdddar
                #:cddddr
                #:cdddr
                #:cddr
                #:cdr
                #:ceiling
                #:complexp
                #:compute-applicable-methods
                #:concatenate
                #:concatenated-stream-streams
                #:conjugate
                #:cons
                #:consp
                #:constantly
                #:slot-boundp
                #:slot-exists-p
                #:slot-value
                #:some
                #:values
                #:values-list
                #:vector
                #:vectorp
                #:wild-pathname-p
                #:with-slots
                #:quote
                #:identity
                #:imagpart
                #:input-stream-p
                #:graphic-char-p
                #:hash-table-count
                #:hash-table-p
                #:hash-table-rehash-size
                #:hash-table-rehash-threshold
                #:hash-table-size
                #:hash-table-test
                #:host-namestring
                #:seventh
                #:signum
                #:simple-bit-vector-p
                #:simple-condition-format-arguments
                #:simple-condition-format-control
                #:simple-string-p
                #:simple-vector-p
                #:sin
                #:sinh
                #:sixth
                #:special-operator-p
                #:sqrt
                #:standard-char-p
                #:stream-element-type
                #:stream-error-stream
                #:stream-external-format
                #:streamp
                #:make-list
                #:make-package
                #:make-pathname
                #:make-random-state
                #:make-sequence
                #:make-string
                #:make-string-input-stream
                #:make-string-output-stream
                #:make-symbol
                #:make-synonym-stream
                #:make-two-way-stream
                #:mapcar
                #:maplist
                #:mask-field
                #:max
                #:member
                #:member-if
                #:member-if-not
                #:merge-pathnames
                #:method-qualifiers
                #:min
                #:minusp
                #:mismatch
                #:mod
                #:multiple-value-call
                #:multiple-value-list
                #:name-char
                #:namestring
                #:ninth
                #:not
                #:notany
                #:notevery
                #:cell-error-name
                #:char
                #:char-code
                #:char-downcase
                #:char-equal
                #:char-greaterp
                #:char-int
                #:char-lessp
                #:char-name
                #:char-not-equal
                #:char-not-greaterp
                #:char-not-lessp
                #:char-upcase
                #:char/=
                #:char<
                #:char<=
                #:char=
                #:char>
                #:char>=
                #:character
                #:characterp
                #:cis
                #:class-name
                #:class-of
                #:code-char
                #:coerce
                #:complement
                #:complex
                #:constantp
                #:copy-alist
                #:copy-list
                #:copy-pprint-dispatch
                #:copy-readtable
                #:copy-seq
                #:copy-structure
                #:copy-symbol
                #:copy-tree
                #:cos
                #:cosh
                #:count
                #:count-if
                #:count-if-not
                #:decode-float
                #:decode-universal-time)
  (:export #:*
           #:+
           #:-
           #:/=
           #:1+
           #:1-
           #:<
           #:<=
           #:=
           #:>
           #:>=
           #:abs
           #:acons
           #:acos
           #:acosh
           #:adjoin
           #:adjustable-array-p
           #:allocate-instance
           #:alpha-char-p
           #:alphanumericp
           #:and
           #:append
           #:apply
           #:apropos-list
           #:aref
           #:atanh
           #:atom
           #:bit
           #:caadr
           #:caar
           #:cadaar
           #:cadadr
           #:cadar
           #:caddar
           #:cadddr
           #:caddr
           #:cadr
           #:car
           #:cdaaar
           #:cdaadr
           #:cdaar
           #:cdadar
           #:cdaddr
           #:cdadr
           #:cdar
           #:cddaar
           #:cddadr
           #:cddar
           #:cdddar
           #:cddddr
           #:cdddr
           #:cddr
           #:cdr
           #:ceiling
           #:complexp
           #:compute-applicable-methods
           #:concatenate
           #:concatenated-stream-streams
           #:conjugate
           #:cons
           #:consp
           #:constantly
           #:slot-boundp
           #:slot-exists-p
           #:slot-value
           #:some
           #:values
           #:values-list
           #:vector
           #:vectorp
           #:wild-pathname-p
           #:with-slots
           #:quote
           #:identity
           #:imagpart
           #:input-stream-p
           #:graphic-char-p
           #:hash-table-count
           #:hash-table-p
           #:hash-table-rehash-size
           #:hash-table-rehash-threshold
           #:hash-table-size
           #:hash-table-test
           #:host-namestring
           #:seventh
           #:signum
           #:simple-bit-vector-p
           #:simple-condition-format-arguments
           #:simple-condition-format-control
           #:simple-string-p
           #:simple-vector-p
           #:sin
           #:sinh
           #:sixth
           #:special-operator-p
           #:sqrt
           #:standard-char-p
           #:stream-element-type
           #:stream-error-stream
           #:stream-external-format
           #:streamp
           #:make-list
           #:make-package
           #:make-pathname
           #:make-random-state
           #:make-sequence
           #:make-string
           #:make-string-input-stream
           #:make-string-output-stream
           #:make-symbol
           #:make-synonym-stream
           #:make-two-way-stream
           #:mapcar
           #:maplist
           #:mask-field
           #:max
           #:member
           #:member-if
           #:member-if-not
           #:merge-pathnames
           #:method-qualifiers
           #:min
           #:minusp
           #:mismatch
           #:mod
           #:multiple-value-call
           #:multiple-value-list
           #:name-char
           #:namestring
           #:ninth
           #:not
           #:notany
           #:notevery
           #:cell-error-name
           #:char
           #:char-code
           #:char-downcase
           #:char-equal
           #:char-greaterp
           #:char-int
           #:char-lessp
           #:char-name
           #:char-not-equal
           #:char-not-greaterp
           #:char-not-lessp
           #:char-upcase
           #:char/=
           #:char<
           #:char<=
           #:char=
           #:char>
           #:char>=
           #:character
           #:characterp
           #:cis
           #:class-name
           #:class-of
           #:code-char
           #:coerce
           #:complement
           #:complex
           #:constantp
           #:copy-alist
           #:copy-list
           #:copy-pprint-dispatch
           #:copy-readtable
           #:copy-seq
           #:copy-structure
           #:copy-symbol
           #:copy-tree
           #:cos
           #:cosh
           #:count
           #:count-if
           #:count-if-not
           #:decode-float
           #:decode-universal-time))
