;;;; package containing all the pure forms from common lisp
;;;; functions or macros that do not modify the inputs or perform visible
;;;; flow control, and that only operate on their arguments. e.g. > equal sqrt

(defpackage #:cl-pure
  (:use #:tamei-common)
  (:import-from :cl
                #:*
                #:+
                #:-
                #:/=
                #:1+
                #:1-
                #:<
                #:<=
                #:=
                #:>
                #:>=
                #:abs
                #:acons
                #:acos
                #:acosh
                #:adjoin
                #:atanh
                #:atom
                #:bit
                #:caadr
                #:caar
                #:cadaar
                #:cadadr
                #:cadar
                #:caddar
                #:cadddr
                #:caddr
                #:cadr
                #:car
                #:cdaaar
                #:cdaadr
                #:cdaar
                #:cdadar
                #:cdaddr
                #:cdadr
                #:cdar
                #:cddaar
                #:cddadr
                #:cddar
                #:cdddar
                #:cddddr
                #:cdddr
                #:cddr
                #:cdr
                #:ceiling
                #:complexp
                #:compute-applicable-methods
                #:concatenate
                #:concatenated-stream-streams
                #:conjugate
                #:cons
                #:consp
                #:constantly
                #:slot-boundp
                #:slot-exists-p
                #:slot-value
                #:some
                #:values
                #:values-list
                #:vector
                #:vectorp
                #:wild-pathname-p
                #:with-slots
                #:quote
                #:identity
                #:imagpart
                #:input-stream-p
                #:graphic-char-p
                #:hash-table-count
                #:hash-table-p
                #:hash-table-rehash-size
                #:hash-table-rehash-threshold
                #:hash-table-size
                #:hash-table-test
                #:host-namestring
                #:seventh
                #:signum
                #:simple-bit-vector-p
                #:simple-condition-format-arguments
                #:simple-condition-format-control
                #:simple-string-p
                #:simple-vector-p
                #:sin
                #:sinh
                #:sixth
                #:special-operator-p
                #:sqrt
                #:standard-char-p
                #:stream-element-type
                #:stream-error-stream
                #:stream-external-format
                #:streamp)
  (:export #:*
           #:+
           #:-
           #:/=
           #:1+
           #:1-
           #:<
           #:<=
           #:=
           #:>
           #:>=
           #:abs
           #:acons
           #:acos
           #:acosh
           #:adjoin
           #:atanh
           #:atom
           #:bit
           #:caadr
           #:caar
           #:cadaar
           #:cadadr
           #:cadar
           #:caddar
           #:cadddr
           #:caddr
           #:cadr
           #:car
           #:cdaaar
           #:cdaadr
           #:cdaar
           #:cdadar
           #:cdaddr
           #:cdadr
           #:cdar
           #:cddaar
           #:cddadr
           #:cddar
           #:cdddar
           #:cddddr
           #:cdddr
           #:cddr
           #:cdr
           #:ceiling
           #:complexp
           #:compute-applicable-methods
           #:concatenate
           #:concatenated-stream-streams
           #:conjugate
           #:cons
           #:consp
           #:constantly
           #:slot-boundp
           #:slot-exists-p
           #:slot-value
           #:some
           #:values
           #:values-list
           #:vector
           #:vectorp
           #:wild-pathname-p
           #:with-slots
           #:quote
           #:identity
           #:imagpart
           #:input-stream-p
           #:graphic-char-p
           #:hash-table-count
           #:hash-table-p
           #:hash-table-rehash-size
           #:hash-table-rehash-threshold
           #:hash-table-size
           #:hash-table-test
           #:host-namestring
           #:seventh
           #:signum
           #:simple-bit-vector-p
           #:simple-condition-format-arguments
           #:simple-condition-format-control
           #:simple-string-p
           #:simple-vector-p
           #:sin
           #:sinh
           #:sixth
           #:special-operator-p
           #:sqrt
           #:standard-char-p
           #:stream-element-type
           #:stream-error-stream
           #:stream-external-format
           #:streamp))
