
(uiop:define-package #:tamei.uncategorized.variables (:use :cl)
  (:export
   :*
   :**
   :***
   :*break-on-signals*
   :*compile-file-pathname*
   :*compile-file-truename*
   :*compile-print*
   :*compile-verbose*
   :*debug-io*
   :*debugger-hook*
   :*default-pathname-defaults*
   :*error-output*
   :*features*
   :*gensym-counter*
   :*load-pathname*
   :*load-print*
   :*load-truename*
   :*load-verbose*
   :*macroexpand-hook*
   :*modules*
   :*package*
   :*print-array*
   :*print-base*
   :*print-case*
   :*print-circle*
   :*print-escape*
   :*print-gensym*
   :*print-length*
   :*print-level*
   :*print-lines*
   :*print-miser-width*
   :*print-pprint-dispatch*
   :*print-pretty*
   :*print-radix*
   :*print-readably*
   :*print-right-margin*
   :*query-io*
   :*random-state*
   :*read-base*
   :*read-default-float-format*
   :*read-eval*
   :*read-suppress*
   :*readtable*
   :*standard-input*
   :*standard-output*
   :*terminal-io*
   :*trace-output*
   :+
   :++
   :+++
   :-
   :/
   ://
   :///))
