
(uiop:define-package #:tamei.uncategorized.symbols (:use :cl)
  (:export
   :&allow-other-keys
   :&aux
   :&body
   :&environment
   :&key
   :&optional
   :&rest
   :&whole
   :call-next-method
   :compilation-speed
   :compiler-macro
   :debug
   :declaration
   :declare
   :dynamic-extent
   :ftype
   :ignorable
   :ignore
   :inline
   :make-method
   :nbutlast
   :nconc
   :next-method-p
   :nintersection
   :notinline
   :nreconc
   :optimize
   :otherwise
   :safety
   :satisfies
   :space
   :special
   :speed
   :standard
   :structure
   :translate-logical-pathname
   :type
   :variable))
