
(uiop:define-package #:tamei.uncategorized.types (:use :cl)
  (:export
   :arithmetic-error
   :array
   :array-rank
   :array-total-size
   :atom
   :base-char
   :base-string
   :bignum
   :bit
   :bit-vector
   :boolean
   :broadcast-stream
   :built-in-class
   :cell-error
   :char-code
   :char-int
   :character
   :class
   :compiled-function
   :complex
   :concatenated-stream
   :condition
   :cons
   :control-error
   :division-by-zero
   :double-float
   :echo-stream
   :end-of-file
   :error
   :extended-char
   :file-error
   :file-stream
   :fixnum
   :float
   :float-digits
   :float-radix
   :floating-point-inexact
   :floating-point-invalid-operation
   :floating-point-overflow
   :floating-point-underflow
   :function
   :generic-function
   :hash-table
   :integer
   :keyword
   :list
   :logical-pathname
   :long-float
   :method
   :method-combination
   :null
   :number
   :package
   :package-error
   :parse-error
   :pathname
   :pathname-device
   :pathname-directory
   :pathname-host
   :pathname-name
   :pathname-type
   :pathname-version
   :print-not-readable
   :program-error
   :random-state
   :ratio
   :rational
   :reader-error
   :readtable
   :real
   :restart
   :sequence
   :serious-condition
   :short-float
   :signed-byte
   :simple-array
   :simple-base-string
   :simple-bit-vector
   :simple-condition
   :simple-error
   :simple-string
   :simple-type-error
   :simple-vector
   :simple-warning
   :single-float
   :standard-char
   :standard-class
   :standard-generic-function
   :standard-method
   :standard-object
   :storage-condition
   :stream
   :stream-error
   :string
   :string-stream
   :structure-class
   :structure-object
   :style-warning
   :symbol
   :synonym-stream
   :t
   :two-way-stream
   :type-error
   :unbound-slot
   :unbound-variable
   :undefined-function
   :unsigned-byte
   :vector
   :warning))
